version: '3'

x-environment_variables: &default-environment_variables
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  JWT_SECRET: ${JWT_SECRET}
  TOKEN_SALT_COMPLEXITY: ${TOKEN_SALT_COMPLEXITY}
  MAGIC_LINK_TOKEN_VALIDITY: ${MAGIC_LINK_TOKEN_VALIDITY}
  REFRESH_TOKEN_VALIDITY: ${REFRESH_TOKEN_VALIDITY}
  ACCESS_TOKEN_VALIDITY: ${ACCESS_TOKEN_VALIDITY}
  SESSION_SECRET: ${SESSION_SECRET}
  REDIRECT_URL: 'http://localhost:3000'
  WHITELISTED_ORIGINS: 'http://localhost:3170,http://localhost:3000,http://localhost:3100'
  VITE_ALLOWED_AUTH_PROVIDERS: 'GOOGLE,GITHUB,MICROSOFT,EMAIL'
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  GOOGLE_CALLBACK_URL: 'http://localhost:3170/v1/auth/google/callback'
  GOOGLE_SCOPE: ${GOOGLE_SCOPE}
  GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
  GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
  GITHUB_CALLBACK_URL: 'http://localhost:3170/v1/auth/github/callback'
  GITHUB_SCOPE: ${GITHUB_SCOPE}
  MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
  MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
  MICROSOFT_CALLBACK_URL: 'http://localhost:3170/v1/auth/microsoft/callback'
  MICROSOFT_SCOPE: ${MICROSOFT_SCOPE}
  MICROSOFT_TENANT: ${MICROSOFT_TENANT}
  MAILER_SMTP_URL: ${MAILER_SMTP_URL}
  MAILER_ADDRESS_FROM: ${MAILER_ADDRESS_FROM}
  RATE_LIMIT_TTL: ${RATE_LIMIT_TTL}
  RATE_LIMIT_MAX: ${RATE_LIMIT_MAX}
  # Base URLs
  VITE_BASE_URL: 'http://localhost:3000'
  VITE_SHORTCODE_BASE_URL: 'http://localhost:3000'
  VITE_ADMIN_URL: 'http://localhost:3100'
  # Backend URLs
  VITE_BACKEND_GQL_URL: 'http://localhost:3170/graphql'
  VITE_BACKEND_WS_URL: 'wss://localhost:3170/graphql'
  VITE_BACKEND_API_URL: 'http://localhost:3170/v1'
  # Terms Of Service And Privacy Policy Links (Optional)
  VITE_APP_TOS_LINK: 'https://docs.hoppscotch.io/terms'
  VITE_APP_PRIVACY_POLICY_LINK: 'https://docs.hoppscotch.io/privacy'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-net

  hoppscotch_backend:
    image: hoppscotch/hoppscotch-backend:latest
    ports:
      - 3170:3170
    environment:
      <<: *default-environment_variables
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hoppscotch-net
      - postgres-net

  hoppscotch_admin:
    image: hoppscotch/hoppscotch-admin:latest
    ports:
      - 3100:8080
    environment:
      <<: *default-environment_variables
    depends_on:
      hoppscotch-backend:
        condition: service_started
    networks:
      - hoppscotch-net

  hoppscotch_frontend:
    image: hoppscotch/hoppscotch-frontend:latest
    ports:
      - 3000:3000
    environment:
      <<: *default-environment_variables
    depends_on:
      hoppscotch-backend:
        condition: service_started
    networks:
      - hoppscotch-net

networks:
  hoppscotch-net:
  postgres-net:
