version: '3'

services:
  node_red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 1880:1880
    networks:
      - public-test-network
    volumes:
      - ./data:/data

networks:
  public-test-network:
    external: true
