version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    networks:
      - php-test-net

  mysql:
    image: mariadb:latest
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: "root-${PASSWORD}.123"
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysqldata/data:/var/lib/mysql/data
      - ./mysqldata/logs:/var/lib/mysql/logs
    networks:
      - mysql-net

  php:
    build:
      context: .
      dockerfile: PHP.dockerfile
    volumes:
      - ./app:/app
    networks:
      - php-test-net
      - mysql-net

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=${USER}
      - PMA_PASSWORD=${PASSWORD}
    volumes:
      - phpmyadmin-sessions:/sessions
      - ./phpmyadmin_theme:/www/themes/theme
    networks:
      - php-test-net
      - mysql-net

volumes:
  mysqldata: {}
  phpmyadmin-sessions: {}

networks:
  php-test-net:
  mysql-net:
